name: build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs==1.3.1 
      - run: pip install mkdocs-material==8.4.2
      - run: mkdocs gh-deploy --force --clean --verbose